#DataSourceProperties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 123456
    #连接池属性 com.zaxxer.hikari.HikariDataSource
    type:  com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      initial-size: 5
      #最小空闲连接
      min-idle: 5
      #超时时间
      max-wait: 3000
    #邮箱设置
  mail:
    username: 
    password: 
    port: 465
    protocol: smtps
    host: smtp.sina.com
    #开启ssl
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #redis
  redis:
    database: 1
    host: localhost
    port: 6379
    #kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000ms
  data:
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 127.0.0.1:9300
  #Spring线程池
  task:
    #普通
    execution:
      pool:
        core-size: 5 #线程池数
        max-size: 15 #最大扩容
        queue-capacity: 100 #队列容量
    #定时
    scheduling:
      pool:
        size: 5
#MybatisProperties
mybatis:
  #映射文件存放位置
  mapper-locations: classpath:mapper/*.xml
  #设置别名
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    #启动自增长主键
    use-generated-keys: true
    #下划线转驼峰
    map-underscore-to-camel-case: true
#设置日志级别
#logging:
#  level:
#    com.nowcoder.community: debug
#默认访问路径
server:
  servlet:
    context-path: "/community"
#community
community:
  path:
    domain: http://localhost:8080
    upload: E:/JAVA-workspace/upload
#生成长图
wk:
  image:
    command: d:/JavaTools/wkhtmltopdf/bin/wkhtmltoimage
    storage: d:/JavaTools/data/wk-image
#qiniuCloud
qiniu:
  key:
    access: 
    secret: 
  bucket:
    header:
      name: oliver-community-header
      url: http://rpwcmhpdl.hb-bkt.clouddn.com
    share:
      name: oliver-community-share
      url: http://rpwceg07z.hb-bkt.clouddn.com
#caffeine
caffeine:
  posts:
    max-size: 15
    expired-seconds: 180
